/**
 * Official 81 Turkish Provinces with plate numbers and normalized forms.
 */
export const TURKISH_PROVINCES = [
  { plate: 1, name: 'Adana', normalized: 'adana' },
  { plate: 2, name: 'Adıyaman', normalized: 'adiyaman' },
  { plate: 3, name: 'Afyonkarahisar', normalized: 'afyonkarahisar' },
  { plate: 4, name: 'Ağrı', normalized: 'agri' },
  { plate: 5, name: 'Amasya', normalized: 'amasya' },
  { plate: 6, name: 'Ankara', normalized: 'ankara' },
  { plate: 7, name: 'Antalya', normalized: 'antalya' },
  { plate: 8, name: 'Artvin', normalized: 'artvin' },
  { plate: 9, name: 'Aydın', normalized: 'aydin' },
  { plate: 10, name: 'Balıkesir', normalized: 'balikesir' },
  { plate: 11, name: 'Bilecik', normalized: 'bilecik' },
  { plate: 12, name: 'Bingöl', normalized: 'bingol' },
  { plate: 13, name: 'Bitlis', normalized: 'bitlis' },
  { plate: 14, name: 'Bolu', normalized: 'bolu' },
  { plate: 15, name: 'Burdur', normalized: 'burdur' },
  { plate: 16, name: 'Bursa', normalized: 'bursa' },
  { plate: 17, name: 'Çanakkale', normalized: 'canakkale' },
  { plate: 18, name: 'Çankırı', normalized: 'cankiri' },
  { plate: 19, name: 'Çorum', normalized: 'corum' },
  { plate: 20, name: 'Denizli', normalized: 'denizli' },
  { plate: 21, name: 'Diyarbakır', normalized: 'diyarbakir' },
  { plate: 22, name: 'Edirne', normalized: 'edirne' },
  { plate: 23, name: 'Elazığ', normalized: 'elazig' },
  { plate: 24, name: 'Erzincan', normalized: 'erzincan' },
  { plate: 25, name: 'Erzurum', normalized: 'erzurum' },
  { plate: 26, name: 'Eskişehir', normalized: 'eskisehir' },
  { plate: 27, name: 'Gaziantep', normalized: 'gaziantep' },
  { plate: 28, name: 'Giresun', normalized: 'giresun' },
  { plate: 29, name: 'Gümüşhane', normalized: 'gumushane' },
  { plate: 30, name: 'Hakkari', normalized: 'hakkari' },
  { plate: 31, name: 'Hatay', normalized: 'hatay' },
  { plate: 32, name: 'Isparta', normalized: 'isparta' },
  { plate: 33, name: 'Mersin', normalized: 'mersin' },
  { plate: 34, name: 'İstanbul', normalized: 'istanbul' },
  { plate: 35, name: 'İzmir', normalized: 'izmir' },
  { plate: 36, name: 'Kars', normalized: 'kars' },
  { plate: 37, name: 'Kastamonu', normalized: 'kastamonu' },
  { plate: 38, name: 'Kayseri', normalized: 'kayseri' },
  { plate: 39, name: 'Kırklareli', normalized: 'kirklareli' },
  { plate: 40, name: 'Kırşehir', normalized: 'kirsehir' },
  { plate: 41, name: 'Kocaeli', normalized: 'kocaeli' },
  { plate: 42, name: 'Konya', normalized: 'konya' },
  { plate: 43, name: 'Kütahya', normalized: 'kutahya' },
  { plate: 44, name: 'Malatya', normalized: 'malatya' },
  { plate: 45, name: 'Manisa', normalized: 'manisa' },
  { plate: 46, name: 'Kahramanmaraş', normalized: 'kahramanmaras' },
  { plate: 47, name: 'Mardin', normalized: 'mardin' },
  { plate: 48, name: 'Muğla', normalized: 'mugla' },
  { plate: 49, name: 'Muş', normalized: 'mus' },
  { plate: 50, name: 'Nevşehir', normalized: 'nevsehir' },
  { plate: 51, name: 'Niğde', normalized: 'nigde' },
  { plate: 52, name: 'Ordu', normalized: 'ordu' },
  { plate: 53, name: 'Rize', normalized: 'rize' },
  { plate: 54, name: 'Sakarya', normalized: 'sakarya' },
  { plate: 55, name: 'Samsun', normalized: 'samsun' },
  { plate: 56, name: 'Siirt', normalized: 'siirt' },
  { plate: 57, name: 'Sinop', normalized: 'sinop' },
  { plate: 58, name: 'Sivas', normalized: 'sivas' },
  { plate: 59, name: 'Tekirdağ', normalized: 'tekirdag' },
  { plate: 60, name: 'Tokat', normalized: 'tokat' },
  { plate: 61, name: 'Trabzon', normalized: 'trabzon' },
  { plate: 62, name: 'Tunceli', normalized: 'tunceli' },
  { plate: 63, name: 'Şanlıurfa', normalized: 'sanliurfa' },
  { plate: 64, name: 'Uşak', normalized: 'usak' },
  { plate: 65, name: 'Van', normalized: 'van' },
  { plate: 66, name: 'Yozgat', normalized: 'yozgat' },
  { plate: 67, name: 'Zonguldak', normalized: 'zonguldak' },
  { plate: 68, name: 'Aksaray', normalized: 'aksaray' },
  { plate: 69, name: 'Bayburt', normalized: 'bayburt' },
  { plate: 70, name: 'Karaman', normalized: 'karaman' },
  { plate: 71, name: 'Kırıkkale', normalized: 'kirikkale' },
  { plate: 72, name: 'Batman', normalized: 'batman' },
  { plate: 73, name: 'Şırnak', normalized: 'sirnak' },
  { plate: 74, name: 'Bartın', normalized: 'bartin' },
  { plate: 75, name: 'Ardahan', normalized: 'ardahan' },
  { plate: 76, name: 'Iğdır', normalized: 'igdir' },
  { plate: 77, name: 'Yalova', normalized: 'yalova' },
  { plate: 78, name: 'Karabük', normalized: 'karabuk' },
  { plate: 79, name: 'Kilis', normalized: 'kilis' },
  { plate: 80, name: 'Osmaniye', normalized: 'osmaniye' },
  { plate: 81, name: 'Düzce', normalized: 'duzce' },
] as const;

export const PROVINCE_NAMES = TURKISH_PROVINCES.map((p) => p.name);
export const PROVINCE_NORMALIZED = TURKISH_PROVINCES.map((p) => p.normalized);

export function isValidProvince(value: string): boolean {
  const norm = value.trim().toLowerCase();
  return TURKISH_PROVINCES.some((p) => p.normalized === norm || p.name.toLowerCase() === norm);
}
